platform :ios, '9.0'

target 'Sister-v1' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!

    # Pods for Sister-v1
    pod 'Kingfisher'
    pod 'Alamofire'
    pod 'KYCircularProgress'
    pod 'SnapKit'
    pod 'GrowingTextView'
end
